### ISSUE TITLE
Integrate it in home assistant or homebridge 

### ISSUE THREAD

**Issue by 27andrea** [fastfend/HaierACBridge#2]
HI can you integrate it in home assistant or homebridge?
I can't use the android application because i would turn on the ac when my android Phone is out of home 
Thanks

**Comment by fastfend** [comment]
[See this](https://github.com/fastfend/HaierACBridge/wiki/How-to-install-it-without-Android-device%3F)
Sry for now it is only solution. Can't see any option to change it. I propose using [homebridge-haier-ac](https://github.com/bstuff/haier-ac-remote/tree/master/packages/homebridge-haier-ac) if you have no option to emulate Android device
