### ISSUE TITLE
Help with integrating

### ISSUE THREAD

**Issue by TomBenSinai** [fastfend/HaierACBridge#3]
Hey. Sorry for the dumb question, but where and how do I access the api?

**Comment by fastfend** [comment]
Hi, I'll add documentation today :)

**Comment by TomBenSinai** [comment]
Thanks.

**Comment by TomBenSinai** [comment]
Hey again. Are you going to expand more in the documentation? I don't quit understand where do I execute it?

**Comment by fastfend** [comment]
Sry this temporary thing on Wiki is not documentation ;) I'll do it ASAP, but I haven't had much time recently. Be patient I won't forget about you :)

**Comment by TomBenSinai** [comment]
Hey again. Still waiting for the documentation. If you can just give me a little explanation on how I use it, it will be great!

**Comment by jjolmo** [comment]
> Hey again. Still waiting for the documentation. If you can just give me a little explanation on how I use it, it will be great!

You can decipher some of the information, methods, calls and params required in the file `HaierACBridge/app/src/main/java/com/fastfend/haieracbridge/webserver/ServerFactory.java`

I did some POST / GET tests and it seems working in my unit. My idea is to create an app to control the AC outside the homebridge system and outside the horrible SmartAir2 app. And this project fits perfectly on this purpose. Here are some examples. These are done on node.js but the get/post interface is universal

$token = Haier AC Token, you can get it in HaierACBridge app once connected

$headers: 
```
const headers = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, PATCH, DELETE', // If needed
  'Access-Control-Allow-Headers': 'X-Requested-With,content-type', // If needed
  'Access-Control-Allow-Credentials': true, // If needed
  token: $token,
};
````
$phoneIp: ip where HaierACBridge is working. You can check it on the HaierACBridge app

GET: get devices
```
 const url = 'http://$phoneIp:10000/listDevices';
  const results = await fetch(url, {
    headers: $headers
  });
```
Then you need to copy the MAC of the device that you want to configure

$deviceId: specific device id you want to control

POST: change temp
```
 const url = 'http://$phoneIp:10000/tempset';
 const results = await fetch(url, {
    method: 'POST',
    body: JSON.stringify({
      tempset: 25,
    }),
    headers: {
      ...headers,
      id: $deviceId
    },
  });
```

hope it helps
@fastfend Many thanks for bringing this project. It helped me tons.

**Comment by TomBenSinai** [comment]
Wow! You really did not forget!
Thank you so much for your help. Hope i'll have the time to use it for my
AC.

**Comment by fastfend** [comment]
Thanks for resolving it for me. Sorry that I don't have time for supporting this project
