### ISSUE TITLE
Haier Smart vs Haier SmartAir2

### ISSUE THREAD

**Issue by poom** [fastfend/HaierACBridge#5]
I try to add HSU-13VNR03T (W) to SmartAir2 app. It always failed but I can added it to Haier Smart app

and this app (Haier AC Bridge) cannot use login and password for Haier Smart.

Can you add login to support the Haier Smart App?

Haier SmartAir2 - https://apps.apple.com/th/app/haiersmartair2/id1065427433

Haier Smart - https://apps.apple.com/th/app/haier-smart/id1477182938

Thank you

**Comment by fastfend** [comment]
Hmm if you could provide me android version of that other app i could see what is going on out there

**Comment by poom** [comment]
Haier Smart Android - https://play.google.com/store/apps/details?id=com.haier.uhome.uplus.seasia

**Comment by fastfend** [comment]
I've done some research and sadly it is completly different architecture. Maybe I'll try later
