### ISSUE TITLE
It still works well but... home assistant ?

### ISSUE THREAD

**Issue by Alexdelgadodiaz** [fastfend/HaierACBridge#7]
Hi there,

I have been testing and it works like a charm with homebridge, but could it be possible to integrate it with home assistant? 

I am not sure if by creating an integration I could connect it with this app replicating the instructions that you use in your homebridge plugin?

**Comment by fastfend** [comment]
Of course it is possible to integrate it with any other apps like homebridge. Sadly this is not what I plan. Aprox. next month I'll get my Homey. This is platform I'm planning to move to. Having that in mind I also plan of some rework for HaierACBridge. Maybe finally I will crack how to talk with AC units to bypass whole Android dependency

EDIT: [This](https://github.com/fastfend/homebridge-haieracbridge-platform/blob/master/src/api.js) is what you can use as starting point
